<?php

namespace Database\Seeders;

use App\Models\Provinsi;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KabKotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public static function run()
    {
        $kabkota = [
            ['kode' => '1101', 'nama' => 'Kabupaten Aceh Besar', 'akronim' => 'AB', 'id_prov' => 1],
            ['kode' => '1102', 'nama' => 'Kabupaten Aceh Jaya', 'akronim' => 'AJ', 'id_prov' => 1],
            ['kode' => '1201', 'nama' => 'Kota Medan', 'akronim' => 'MDN', 'id_prov' => 2],
            ['kode' => '1202', 'nama' => 'Kabupaten Deli Serdang', 'akronim' => 'DS', 'id_prov' => 2],
            // Lanjutkan dengan daftar kabupaten dan kota lainnya
            ['kode' => '3301', 'nama' => 'Kabupaten Cilacap', 'akronim' => 'CIL', 'id_prov' => 19],
            ['kode' => '3302', 'nama' => 'Kabupaten Banyumas', 'akronim' => 'BAN', 'id_prov' => 19],
            ['kode' => '3303', 'nama' => 'Kabupaten Purbalingga', 'akronim' => 'PUR', 'id_prov' => 19],
            ['kode' => '3304', 'nama' => 'Kabupaten Banjarnegara', 'akronim' => 'BANJAR', 'id_prov' => 19],
            ['kode' => '3305', 'nama' => 'Kabupaten Kebumen', 'akronim' => 'KEBUMEN', 'id_prov' => 19],
            ['kode' => '3306', 'nama' => 'Kabupaten Purworejo', 'akronim' => 'PURWOREJO', 'id_prov' => 19],
            ['kode' => '3311', 'nama' => 'Kabupaten Wonosobo', 'akronim' => 'WONOSOBO', 'id_prov' => 19],
            ['kode' => '3312', 'nama' => 'Kabupaten Magelang', 'akronim' => 'MAGELANG', 'id_prov' => 19],
            ['kode' => '3313', 'nama' => 'Kabupaten Boyolali', 'akronim' => 'BOYOLALI', 'id_prov' => 19],
            ['kode' => '3314', 'nama' => 'Kabupaten Klaten', 'akronim' => 'KLATEN', 'id_prov' => 19],
            // Lanjutkan dengan daftar kabupaten dan kota lainnya di Jawa Tengah
        ];

        $kabkota = [
            ['kode' => '1101', 'nama' => 'Kabupaten Aceh Selatan', 'akronim' => 'TTN', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1102', 'nama' => 'Kabupaten Aceh Tenggara', 'akronim' => 'KTN', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1103', 'nama' => 'Kabupaten Aceh Timur', 'akronim' => 'LGS', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1104', 'nama' => 'Kabupaten Aceh Tengah', 'akronim' => 'TKN', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1105', 'nama' => 'Kabupaten Aceh Barat', 'akronim' => 'MBO', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1106', 'nama' => 'Kabupaten Aceh Besar', 'akronim' => 'JTH', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1107', 'nama' => 'Kabupaten Pidie', 'akronim' => 'SGI', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1108', 'nama' => 'Kabupaten Aceh Utara', 'akronim' => 'LSK', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1109', 'nama' => 'Kabupaten Simeulue', 'akronim' => 'SNB', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1110', 'nama' => 'Kabupaten Aceh Singkil', 'akronim' => 'SKL', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1111', 'nama' => 'Kabupaten Bireuen', 'akronim' => 'BIR', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1112', 'nama' => 'Kabupaten Aceh Barat Daya', 'akronim' => 'BPD', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1113', 'nama' => 'Kabupaten Gayo Lues', 'akronim' => 'BKJ', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1114', 'nama' => 'Kabupaten Aceh Jaya', 'akronim' => 'CAG', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1115', 'nama' => 'Kabupaten Nagan Raya', 'akronim' => 'SKM', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1116', 'nama' => 'Kabupaten Aceh Tamiang', 'akronim' => 'KRB', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1117', 'nama' => 'Kabupaten Bener Meriah', 'akronim' => 'STR', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1118', 'nama' => 'Kabupaten Pidie Jaya', 'akronim' => 'MRN', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1171', 'nama' => 'Kota Banda Aceh', 'akronim' => 'BNA', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1172', 'nama' => 'Kota Sabang', 'akronim' => 'SAB', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1173', 'nama' => 'Kota Lhokseumawe', 'akronim' => 'LSM', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1174', 'nama' => 'Kota Langsa', 'akronim' => 'LGS', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1175', 'nama' => 'Kota Subulussalam', 'akronim' => 'SUS', 'kode_prov' => '11', 'id_prov' => Provinsi::where('kode', '11')->first()->id],
            ['kode' => '1201', 'nama' => 'Kabupaten Tapanuli Tengah', 'akronim' => 'SBG', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1202', 'nama' => 'Kabupaten Tapanuli Utara', 'akronim' => 'TRT', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1203', 'nama' => 'Kabupaten Tapanuli Selatan', 'akronim' => 'PSP', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1204', 'nama' => 'Kabupaten Nias', 'akronim' => 'GST', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1205', 'nama' => 'Kabupaten Langkat', 'akronim' => 'STB', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1206', 'nama' => 'Kabupaten Karo', 'akronim' => 'KBJ', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1207', 'nama' => 'Kabupaten Deli Serdang', 'akronim' => 'LBP', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1208', 'nama' => 'Kabupaten Simalungun', 'akronim' => 'PMS', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1209', 'nama' => 'Kabupaten Asahan', 'akronim' => 'KIS', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1210', 'nama' => 'Kabupaten Labuhanbatu', 'akronim' => 'RAP', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1211', 'nama' => 'Kabupaten Dairi', 'akronim' => 'SDK', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1212', 'nama' => 'Kabupaten Toba Samosir', 'akronim' => 'BLG', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1213', 'nama' => 'Kabupaten Mandailing Natal', 'akronim' => 'PYB', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1214', 'nama' => 'Kabupaten Nias Selatan', 'akronim' => 'TLD', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1215', 'nama' => 'Kabupaten Pakpak Bharat', 'akronim' => 'SAL', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1216', 'nama' => 'Kabupaten Humbang Hasundutan', 'akronim' => 'DLS', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1217', 'nama' => 'Kabupaten Samosir', 'akronim' => 'PRR', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1218', 'nama' => 'Kabupaten Serdang Bedagai', 'akronim' => 'SRH', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1219', 'nama' => 'Kabupaten Batu Bara', 'akronim' => 'LMP', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1220', 'nama' => 'Kabupaten Padang Lawas Utara', 'akronim' => 'GNT', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1221', 'nama' => 'Kabupaten Padang Lawas', 'akronim' => 'SBH', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1222', 'nama' => 'Kabupaten Labuhanbatu Selatan', 'akronim' => 'KPI', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1223', 'nama' => 'Kabupaten Labuhanbatu Utara', 'akronim' => 'AKK', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1224', 'nama' => 'Kabupaten Nias Utara', 'akronim' => 'LTU', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1225', 'nama' => 'Kabupaten Nias Barat', 'akronim' => 'LHM', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1271', 'nama' => 'Kota Medan', 'akronim' => 'MDN', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1272', 'nama' => 'Kota Pematangsiantar', 'akronim' => 'PMS', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1273', 'nama' => 'Kota Sibolga', 'akronim' => 'SBG', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1274', 'nama' => 'Kota Tanjung Balai', 'akronim' => 'TJB', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1275', 'nama' => 'Kota Binjai', 'akronim' => 'BNJ', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1276', 'nama' => 'Kota Tebing Tinggi', 'akronim' => 'TBT', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1277', 'nama' => 'Kota Padang Sidempuan', 'akronim' => 'PSP', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1278', 'nama' => 'Kota Gunungsitoli', 'akronim' => 'GST', 'kode_prov' => '12', 'id_prov' => Provinsi::where('kode', '12')->first()->id],
            ['kode' => '1301', 'nama' => 'Kabupaten Pesisir Selatan', 'akronim' => 'PNN', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1302', 'nama' => 'Kabupaten Solok', 'akronim' => 'ARS', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1303', 'nama' => 'Kabupaten Sijunjung', 'akronim' => 'MRJ', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1304', 'nama' => 'Kabupaten Tanah Datar', 'akronim' => 'BSK', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1305', 'nama' => 'Kabupaten Padang Pariaman', 'akronim' => 'NPM', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1306', 'nama' => 'Kabupaten Agam', 'akronim' => 'LBB', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1307', 'nama' => 'Kabupaten Lima Puluh Kota', 'akronim' => 'SRK', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1308', 'nama' => 'Kabupaten Pasaman', 'akronim' => 'LBS', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1309', 'nama' => 'Kabupaten Kepulauan Mentawai', 'akronim' => 'TPT', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1310', 'nama' => 'Kabupaten Dharmasraya', 'akronim' => 'PLJ', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1311', 'nama' => 'Kabupaten Solok Selatan', 'akronim' => 'PDA', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1312', 'nama' => 'Kabupaten Pasaman Barat', 'akronim' => 'SPE', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1371', 'nama' => 'Kota Padang', 'akronim' => 'PAD', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1372', 'nama' => 'Kota Solok', 'akronim' => 'SLK', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1373', 'nama' => 'Kota Sawahlunto', 'akronim' => 'SWL', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1374', 'nama' => 'Kota Padang Panjang', 'akronim' => 'PDP', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1375', 'nama' => 'Kota Bukittinggi', 'akronim' => 'BKT', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1376', 'nama' => 'Kota Payakumbuh', 'akronim' => 'PYH', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1377', 'nama' => 'Kota Pariaman', 'akronim' => 'PMN', 'kode_prov' => '13', 'id_prov' => Provinsi::where('kode', '13')->first()->id],
            ['kode' => '1401', 'nama' => 'Kabupaten Kampar', 'akronim' => 'BKN', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1402', 'nama' => 'Kabupaten Indragiri Hulu', 'akronim' => 'RGT', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1403', 'nama' => 'Kabupaten Bengkalis', 'akronim' => 'BLS', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1404', 'nama' => 'Kabupaten Indragiri Hilir', 'akronim' => 'TBH', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1405', 'nama' => 'Kabupaten Pelalawan', 'akronim' => 'PKK', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1406', 'nama' => 'Kabupaten Rokan Hulu', 'akronim' => 'PRP', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1407', 'nama' => 'Kabupaten Rokan Hilir', 'akronim' => 'UJT', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1408', 'nama' => 'Kabupaten Siak', 'akronim' => 'SAK', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1409', 'nama' => 'Kabupaten Kuantan Singingi', 'akronim' => 'TLK', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1410', 'nama' => 'Kabupaten Kepulauan Meranti', 'akronim' => 'TTG', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1471', 'nama' => 'Kota Pekanbaru', 'akronim' => 'PBR', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1472', 'nama' => 'Kota Dumai', 'akronim' => 'DUM', 'kode_prov' => '14', 'id_prov' => Provinsi::where('kode', '14')->first()->id],
            ['kode' => '1501', 'nama' => 'Kabupaten Kerinci', 'akronim' => 'SPN', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1502', 'nama' => 'Kabupaten Merangin', 'akronim' => 'BKO', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1503', 'nama' => 'Kabupaten Sarolangun', 'akronim' => 'SRL', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1504', 'nama' => 'Kabupaten Batanghari', 'akronim' => 'MBN', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1505', 'nama' => 'Kabupaten Muaro Jambi', 'akronim' => 'SNT', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1506', 'nama' => 'Kabupaten Tanjung Jabung Barat', 'akronim' => 'KLT', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1507', 'nama' => 'Kabupaten Tanjung Jabung Timur', 'akronim' => 'MSK', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1508', 'nama' => 'Kabupaten Bungo', 'akronim' => 'MRB', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1509', 'nama' => 'Kabupaten Tebo', 'akronim' => 'MRT', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1571', 'nama' => 'Kota Jambi', 'akronim' => 'JMB', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1572', 'nama' => 'Kota Sungai Penuh', 'akronim' => 'SPN', 'kode_prov' => '15', 'id_prov' => Provinsi::where('kode', '15')->first()->id],
            ['kode' => '1601', 'nama' => 'Kabupaten Ogan Komering Ulu', 'akronim' => 'BTA', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1602', 'nama' => 'Kabupaten Ogan Komering Ilir', 'akronim' => 'KAG', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1603', 'nama' => 'Kabupaten Muara Enim', 'akronim' => 'MRE', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1604', 'nama' => 'Kabupaten Lahat', 'akronim' => 'LHT', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1605', 'nama' => 'Kabupaten Musi Rawas', 'akronim' => 'MBL', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1606', 'nama' => 'Kabupaten Musi Banyuasin', 'akronim' => 'SKY', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1607', 'nama' => 'Kabupaten Banyuasin', 'akronim' => 'PKB', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1608', 'nama' => 'Kabupaten Ogan Komering Ulu Timur', 'akronim' => 'MPR', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1609', 'nama' => 'Kabupaten Ogan Komering Ulu Selatan', 'akronim' => 'MRD', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1610', 'nama' => 'Kabupaten Ogan Ilir', 'akronim' => 'IDL', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1611', 'nama' => 'Kabupaten Empat Lawang', 'akronim' => 'TBG', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1612', 'nama' => 'Kabupaten Penukal Abab Lematang Ilir', 'akronim' => 'PALI', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1613', 'nama' => 'Kabupaten Musi Rawas Utara', 'akronim' => 'MURATARA', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1671', 'nama' => 'Kota Palembang', 'akronim' => 'PLG', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1672', 'nama' => 'Kota Pagar Alam', 'akronim' => 'PGAM', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1673', 'nama' => 'Kota Lubuk Linggau', 'akronim' => 'LLG', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1674', 'nama' => 'Kota Prabumulih', 'akronim' => 'PBM', 'kode_prov' => '16', 'id_prov' => Provinsi::where('kode', '16')->first()->id],
            ['kode' => '1701', 'nama' => 'Kabupaten Bengkulu Selatan', 'akronim' => 'MANNA', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1702', 'nama' => 'Kabupaten Rejang Lebong', 'akronim' => 'CRP', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1703', 'nama' => 'Kabupaten Bengkulu Utara', 'akronim' => 'AGM', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1704', 'nama' => 'Kabupaten Kaur', 'akronim' => 'BHN', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1705', 'nama' => 'Kabupaten Seluma', 'akronim' => 'TAS', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1706', 'nama' => 'Kabupaten Muko Muko', 'akronim' => 'MKM', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1707', 'nama' => 'Kabupaten Lebong', 'akronim' => 'TUB', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1708', 'nama' => 'Kabupaten Kepahiang', 'akronim' => 'KPH', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1709', 'nama' => 'Kabupaten Bengkulu Tengah', 'akronim' => 'KRT', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1771', 'nama' => 'Kota Bengkulu', 'akronim' => 'BGL', 'kode_prov' => '17', 'id_prov' => Provinsi::where('kode', '17')->first()->id],
            ['kode' => '1801', 'nama' => 'Kabupaten Lampung Selatan', 'akronim' => 'KLA', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1802', 'nama' => 'Kabupaten Lampung Tengah', 'akronim' => 'GNS', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1803', 'nama' => 'Kabupaten Lampung Utara', 'akronim' => 'KTB', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1804', 'nama' => 'Kabupaten Lampung Barat', 'akronim' => 'LIW', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1805', 'nama' => 'Kabupaten Tulang Bawang', 'akronim' => 'MGL', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1806', 'nama' => 'Kabupaten Tanggamus', 'akronim' => 'KOT', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1807', 'nama' => 'Kabupaten Lampung Timur', 'akronim' => 'SDN', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1808', 'nama' => 'Kabupaten Way Kanan', 'akronim' => 'BBU', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1809', 'nama' => 'Kabupaten Pesawaran', 'akronim' => 'GDT', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1810', 'nama' => 'Kabupaten Pringsewu', 'akronim' => 'PRW', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1811', 'nama' => 'Kabupaten Mesuji', 'akronim' => 'MSJ', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1812', 'nama' => 'Kabupaten Tulang Bawang Barat', 'akronim' => 'TWG', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1813', 'nama' => 'Kabupaten Pesisir Barat', 'akronim' => '   ', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id], // Nama kabupaten kosong (sesuai dengan data yang diberikan)
            ['kode' => '1871', 'nama' => 'Kota Bandar Lampung', 'akronim' => 'BDL', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1872', 'nama' => 'Kota Metro', 'akronim' => 'MET', 'kode_prov' => '18', 'id_prov' => Provinsi::where('kode', '18')->first()->id],
            ['kode' => '1901', 'nama' => 'Kabupaten Bangka', 'akronim' => 'SGL', 'kode_prov' => '19', 'id_prov' => Provinsi::where('kode', '19')->first()->id],
            ['kode' => '1902', 'nama' => 'Kabupaten Belitung', 'akronim' => 'TDN', 'kode_prov' => '19', 'id_prov' => Provinsi::where('kode', '19')->first()->id],
            ['kode' => '1903', 'nama' => 'Kabupaten Bangka Selatan', 'akronim' => 'TBL', 'kode_prov' => '19', 'id_prov' => Provinsi::where('kode', '19')->first()->id],
            ['kode' => '1904', 'nama' => 'Kabupaten Bangka Tengah', 'akronim' => 'KBA', 'kode_prov' => '19', 'id_prov' => Provinsi::where('kode', '19')->first()->id],
            ['kode' => '1905', 'nama' => 'Kabupaten Bangka Barat', 'akronim' => 'MTK', 'kode_prov' => '19', 'id_prov' => Provinsi::where('kode', '19')->first()->id],
            ['kode' => '1906', 'nama' => 'Kabupaten Belitung Timur', 'akronim' => 'MGR', 'kode_prov' => '19', 'id_prov' => Provinsi::where('kode', '19')->first()->id],
            ['kode' => '1971', 'nama' => 'Kota Pangkal Pinang', 'akronim' => 'PGP', 'kode_prov' => '19', 'id_prov' => Provinsi::where('kode', '19')->first()->id],
            ['kode' => '2101', 'nama' => 'Kabupaten Bintan', 'akronim' => 'BSB', 'kode_prov' => '21', 'id_prov' => Provinsi::where('kode', '21')->first()->id],
            ['kode' => '2102', 'nama' => 'Kabupaten Karimun', 'akronim' => 'TBK', 'kode_prov' => '21', 'id_prov' => Provinsi::where('kode', '21')->first()->id],
            ['kode' => '2103', 'nama' => 'Kabupaten Natuna', 'akronim' => 'RAN', 'kode_prov' => '21', 'id_prov' => Provinsi::where('kode', '21')->first()->id],
            ['kode' => '2104', 'nama' => 'Kabupaten Lingga', 'akronim' => 'DKL', 'kode_prov' => '21', 'id_prov' => Provinsi::where('kode', '21')->first()->id],
            ['kode' => '2105', 'nama' => 'Kabupaten Kepulauan Anambas', 'akronim' => 'TRP', 'kode_prov' => '21', 'id_prov' => Provinsi::where('kode', '21')->first()->id],
            ['kode' => '2171', 'nama' => 'Kota Batam', 'akronim' => 'BTM', 'kode_prov' => '21', 'id_prov' => Provinsi::where('kode', '21')->first()->id],
            ['kode' => '2172', 'nama' => 'Kota Tanjung Pinang', 'akronim' => 'TPG', 'kode_prov' => '21', 'id_prov' => Provinsi::where('kode', '21')->first()->id],
            ['kode' => '3101', 'nama' => 'Kabupaten Adm Kep Seribu', 'akronim' => 'KSU', 'kode_prov' => '31', 'id_prov' => Provinsi::where('kode', '31')->first()->id],
            ['kode' => '3171', 'nama' => 'Kota Adm Jakarta Pusat', 'akronim' => 'TNA', 'kode_prov' => '31', 'id_prov' => Provinsi::where('kode', '31')->first()->id],
            ['kode' => '3172', 'nama' => 'Kota Adm Jakarta Utara', 'akronim' => 'TJP', 'kode_prov' => '31', 'id_prov' => Provinsi::where('kode', '31')->first()->id],
            ['kode' => '3173', 'nama' => 'Kota Adm Jakarta Barat', 'akronim' => 'GGP', 'kode_prov' => '31', 'id_prov' => Provinsi::where('kode', '31')->first()->id],
            ['kode' => '3174', 'nama' => 'Kota Adm Jakarta Selatan', 'akronim' => 'KYB', 'kode_prov' => '31', 'id_prov' => Provinsi::where('kode', '31')->first()->id],
            ['kode' => '3175', 'nama' => 'Kota Adm Jakarta Timur', 'akronim' => 'CKG', 'kode_prov' => '31', 'id_prov' => Provinsi::where('kode', '31')->first()->id],
            ['kode' => '3201', 'nama' => 'Kabupaten Bogor', 'akronim' => 'CBI', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3202', 'nama' => 'Kabupaten Sukabumi', 'akronim' => 'SBM', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3203', 'nama' => 'Kabupaten Cianjur', 'akronim' => 'CJR', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3204', 'nama' => 'Kabupaten Bandung', 'akronim' => 'COR', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3205', 'nama' => 'Kabupaten Garut', 'akronim' => 'GRT', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3206', 'nama' => 'Kabupaten Tasikmalaya', 'akronim' => 'PALI', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3207', 'nama' => 'Kabupaten Ciamis', 'akronim' => 'CMS', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3208', 'nama' => 'Kabupaten Kuningan', 'akronim' => 'KNG', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3209', 'nama' => 'Kabupaten Cirebon', 'akronim' => 'SBR', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3210', 'nama' => 'Kabupaten Majalengka', 'akronim' => 'MJL', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3211', 'nama' => 'Kabupaten Sumedang', 'akronim' => 'SMD', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3212', 'nama' => 'Kabupaten Indramayu', 'akronim' => 'IDM', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3213', 'nama' => 'Kabupaten Subang', 'akronim' => 'SNG', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3214', 'nama' => 'Kabupaten Purwakarta', 'akronim' => 'PWK', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3215', 'nama' => 'Kabupaten Karawang', 'akronim' => 'KWG', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3216', 'nama' => 'Kabupaten Bekasi', 'akronim' => 'CKR', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3217', 'nama' => 'Kabupaten Bandung Barat', 'akronim' => 'NPH', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3218', 'nama' => 'Kabupaten Pangandaran', 'akronim' => 'PAG', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3271', 'nama' => 'Kota Bogor', 'akronim' => 'BGR', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3272', 'nama' => 'Kota Sukabumi', 'akronim' => 'SKB', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3273', 'nama' => 'Kota Bandung', 'akronim' => 'BDG', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3274', 'nama' => 'Kota Cirebon', 'akronim' => 'CBN', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3275', 'nama' => 'Kota Bekasi', 'akronim' => 'BKS', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3276', 'nama' => 'Kota Depok', 'akronim' => 'DPK', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3277', 'nama' => 'Kota Cimahi', 'akronim' => 'CMH', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3278', 'nama' => 'Kota Tasikmalaya', 'akronim' => 'TSM', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3279', 'nama' => 'Kota Banjar', 'akronim' => 'BJR', 'kode_prov' => '32', 'id_prov' => Provinsi::where('kode', '32')->first()->id],
            ['kode' => '3301', 'nama' => 'Kabupaten Cilacap', 'akronim' => 'CLP', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3302', 'nama' => 'Kabupaten Banyumas', 'akronim' => 'PWT', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3303', 'nama' => 'Kabupaten Purbalingga', 'akronim' => 'PBG', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3304', 'nama' => 'Kabupaten Banjarnegara', 'akronim' => 'BNR', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3305', 'nama' => 'Kabupaten Kebumen', 'akronim' => 'KBM', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3306', 'nama' => 'Kabupaten Purworejo', 'akronim' => 'PWR', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3307', 'nama' => 'Kabupaten Wonosobo', 'akronim' => 'WSB', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3308', 'nama' => 'Kabupaten Magelang', 'akronim' => 'MKD', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3309', 'nama' => 'Kabupaten Boyolali', 'akronim' => 'BYL', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3310', 'nama' => 'Kabupaten Klaten', 'akronim' => 'KLN', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3311', 'nama' => 'Kabupaten Sukoharjo', 'akronim' => 'SKH', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3312', 'nama' => 'Kabupaten Wonogiri', 'akronim' => 'WNG', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3313', 'nama' => 'Kabupaten Karanganyar', 'akronim' => 'KRG', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3314', 'nama' => 'Kabupaten Sragen', 'akronim' => 'SGN', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3315', 'nama' => 'Kabupaten Grobogan', 'akronim' => 'PWD', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3316', 'nama' => 'Kabupaten Blora', 'akronim' => 'BLA', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3317', 'nama' => 'Kabupaten Rembang', 'akronim' => 'RBG', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3318', 'nama' => 'Kabupaten Pati', 'akronim' => 'PTI', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3319', 'nama' => 'Kabupaten Kudus', 'akronim' => 'KDS', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3320', 'nama' => 'Kabupaten Jepara', 'akronim' => 'JPA', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3321', 'nama' => 'Kabupaten Demak', 'akronim' => 'DMK', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3322', 'nama' => 'Kabupaten Semarang', 'akronim' => 'UNR', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3323', 'nama' => 'Kabupaten Temanggung', 'akronim' => 'TMG', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3324', 'nama' => 'Kabupaten Kendal', 'akronim' => 'KDL', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3325', 'nama' => 'Kabupaten Batang', 'akronim' => 'BTG', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3326', 'nama' => 'Kabupaten Pekalongan', 'akronim' => 'KJN', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3327', 'nama' => 'Kabupaten Pemalang', 'akronim' => 'PML', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3328', 'nama' => 'Kabupaten Tegal', 'akronim' => 'SLW', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3329', 'nama' => 'Kabupaten Brebes', 'akronim' => 'BBS', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3371', 'nama' => 'Kota Magelang', 'akronim' => 'MGG', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3372', 'nama' => 'Kota Surakarta', 'akronim' => 'SKT', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3373', 'nama' => 'Kota Salatiga', 'akronim' => 'SLT', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3374', 'nama' => 'Kota Semarang', 'akronim' => 'SMG', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3375', 'nama' => 'Kota Pekalongan', 'akronim' => 'PKL', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3376', 'nama' => 'Kota Tegal', 'akronim' => 'TGL', 'kode_prov' => '33', 'id_prov' => Provinsi::where('kode', '33')->first()->id],
            ['kode' => '3401', 'nama' => 'Kabupaten Kulon Progo', 'akronim' => 'WAT', 'kode_prov' => '34', 'id_prov' => Provinsi::where('kode', '34')->first()->id],
            ['kode' => '3402', 'nama' => 'Kabupaten Bantul', 'akronim' => 'BTL', 'kode_prov' => '34', 'id_prov' => Provinsi::where('kode', '34')->first()->id],
            ['kode' => '3403', 'nama' => 'Kabupaten Gunungkidul', 'akronim' => 'WNO', 'kode_prov' => '34', 'id_prov' => Provinsi::where('kode', '34')->first()->id],
            ['kode' => '3404', 'nama' => 'Kabupaten Sleman', 'akronim' => 'SMN', 'kode_prov' => '34', 'id_prov' => Provinsi::where('kode', '34')->first()->id],
            ['kode' => '3471', 'nama' => 'Kota Yogyakarta', 'akronim' => 'YYK', 'kode_prov' => '34', 'id_prov' => Provinsi::where('kode', '34')->first()->id],
            ['kode' => '3501', 'nama' => 'Kabupaten Pacitan', 'akronim' => 'PCT', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3502', 'nama' => 'Kabupaten Ponorogo', 'akronim' => 'PNG', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3503', 'nama' => 'Kabupaten Trenggalek', 'akronim' => 'TRK', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3504', 'nama' => 'Kabupaten Tulungagung', 'akronim' => 'TLG', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3505', 'nama' => 'Kabupaten Blitar', 'akronim' => 'KNR', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3506', 'nama' => 'Kabupaten Kediri', 'akronim' => 'KDR', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3507', 'nama' => 'Kabupaten Malang', 'akronim' => 'KPN', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3508', 'nama' => 'Kabupaten Lumajang', 'akronim' => 'LMJ', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3509', 'nama' => 'Kabupaten Jember', 'akronim' => 'JMR', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3510', 'nama' => 'Kabupaten Banyuwangi', 'akronim' => 'BYW', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3511', 'nama' => 'Kabupaten Bondowoso', 'akronim' => 'BDW', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3512', 'nama' => 'Kabupaten Situbondo', 'akronim' => 'SIT', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3513', 'nama' => 'Kabupaten Probolinggo', 'akronim' => 'KRS', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3514', 'nama' => 'Kabupaten Pasuruan', 'akronim' => 'PSR', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3515', 'nama' => 'Kabupaten Sidoarjo', 'akronim' => 'SDA', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3516', 'nama' => 'Kabupaten Mojokerto', 'akronim' => 'MJK', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3517', 'nama' => 'Kabupaten Jombang', 'akronim' => 'JBG', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3518', 'nama' => 'Kabupaten Nganjuk', 'akronim' => 'NJK', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3519', 'nama' => 'Kabupaten Madiun', 'akronim' => 'MJY', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3520', 'nama' => 'Kabupaten Magetan', 'akronim' => 'MGT', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3521', 'nama' => 'Kabupaten Ngawi', 'akronim' => 'NGW', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3522', 'nama' => 'Kabupaten Bojonegoro', 'akronim' => 'BJN', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3523', 'nama' => 'Kabupaten Tuban', 'akronim' => 'TBN', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3524', 'nama' => 'Kabupaten Lamongan', 'akronim' => 'LMG', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3525', 'nama' => 'Kabupaten Gresik', 'akronim' => 'GSK', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3526', 'nama' => 'Kabupaten Bangkalan', 'akronim' => 'BKL', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3527', 'nama' => 'Kabupaten Sampang', 'akronim' => 'SPG', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3528', 'nama' => 'Kabupaten Pamekasan', 'akronim' => 'PMK', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3529', 'nama' => 'Kabupaten Sumenep', 'akronim' => 'SMP', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3571', 'nama' => 'Kota Kediri', 'akronim' => 'KDR', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '7407', 'nama' => 'Kabupaten Wakatobi', 'akronim' => 'WGW', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7408', 'nama' => 'Kabupaten Kolaka Utara', 'akronim' => 'LSS', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7409', 'nama' => 'Kabupaten Konawe Utara', 'akronim' => 'WGD', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7410', 'nama' => 'Kabupaten Buton Utara', 'akronim' => 'BNG', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7411', 'nama' => 'Kabupaten Kolaka Timur', 'akronim' => 'TWT', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7412', 'nama' => 'Kabupaten Konawe Kepulauan', 'akronim' => 'LGR', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7413', 'nama' => 'Kabupaten Muna Barat', 'akronim' => 'LWR', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7414', 'nama' => 'Kabupaten Buton Tengah', 'akronim' => 'LBR', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7415', 'nama' => 'Kabupaten Buton Selatan', 'akronim' => 'BTG', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7471', 'nama' => 'Kota Kendari', 'akronim' => 'KDI', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7472', 'nama' => 'Kota Bau Bau', 'akronim' => 'BAU', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7501', 'nama' => 'Kabupaten Gorontalo', 'akronim' => 'GTO', 'kode_prov' => '75', 'id_prov' => Provinsi::where('kode', '75')->first()->id],
            ['kode' => '7502', 'nama' => 'Kabupaten Boalemo', 'akronim' => 'TMT', 'kode_prov' => '75', 'id_prov' => Provinsi::where('kode', '75')->first()->id],
            ['kode' => '7503', 'nama' => 'Kabupaten Bone Bolango', 'akronim' => 'SWW', 'kode_prov' => '75', 'id_prov' => Provinsi::where('kode', '75')->first()->id],
            ['kode' => '7504', 'nama' => 'Kabupaten Pahuwato', 'akronim' => 'MAR', 'kode_prov' => '75', 'id_prov' => Provinsi::where('kode', '75')->first()->id],
            ['kode' => '7505', 'nama' => 'Kabupaten Gorontalo Utara', 'akronim' => 'KWD', 'kode_prov' => '75', 'id_prov' => Provinsi::where('kode', '75')->first()->id],
            ['kode' => '7571', 'nama' => 'Kota Gorontalo', 'akronim' => 'GTO', 'kode_prov' => '75', 'id_prov' => Provinsi::where('kode', '75')->first()->id],
            ['kode' => '7601', 'nama' => 'Kabupaten Pasangkayu', 'akronim' => 'PSY', 'kode_prov' => '76', 'id_prov' => Provinsi::where('kode', '76')->first()->id],
            ['kode' => '7602', 'nama' => 'Kabupaten Mamuju', 'akronim' => 'MAM', 'kode_prov' => '76', 'id_prov' => Provinsi::where('kode', '76')->first()->id],
            ['kode' => '7603', 'nama' => 'Kabupaten Mamasa', 'akronim' => 'MMS', 'kode_prov' => '76', 'id_prov' => Provinsi::where('kode', '76')->first()->id],
            ['kode' => '7604', 'nama' => 'Kabupaten Polewali Mandar', 'akronim' => 'PLW', 'kode_prov' => '76', 'id_prov' => Provinsi::where('kode', '76')->first()->id],
            ['kode' => '7605', 'nama' => 'Kabupaten Majene', 'akronim' => 'MJN', 'kode_prov' => '76', 'id_prov' => Provinsi::where('kode', '76')->first()->id],
            ['kode' => '7606', 'nama' => 'Kabupaten Mamuju Tengah', 'akronim' => 'TBK', 'kode_prov' => '76', 'id_prov' => Provinsi::where('kode', '76')->first()->id],
            ['kode' => '8101', 'nama' => 'Kabupaten Maluku Tengah', 'akronim' => 'MSH', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8102', 'nama' => 'Kabupaten Maluku Tenggara', 'akronim' => 'TUL', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8103', 'nama' => 'Kabupaten Kepulauan Tanimbar', 'akronim' => 'SMK', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8104', 'nama' => 'Kabupaten Buru', 'akronim' => 'NLA', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8105', 'nama' => 'Kabupaten Seram Bagian Timur', 'akronim' => 'DTH', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8106', 'nama' => 'Kabupaten Seram Bagian Barat', 'akronim' => 'DRH', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8107', 'nama' => 'Kabupaten Kepulauan Aru', 'akronim' => 'DOB', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8108', 'nama' => 'Kabupaten Maluku Barat Daya', 'akronim' => 'TKR', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8109', 'nama' => 'Kabupaten Buru Selatan', 'akronim' => 'NMR', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8171', 'nama' => 'Kota Ambon', 'akronim' => 'AMB', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8172', 'nama' => 'Kota Tual', 'akronim' => 'TUL', 'kode_prov' => '81', 'id_prov' => Provinsi::where('kode', '81')->first()->id],
            ['kode' => '8201', 'nama' => 'Kabupaten Halmahera Barat', 'akronim' => 'JLL', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '8202', 'nama' => 'Kabupaten Halmahera Tengah', 'akronim' => 'WED', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '8203', 'nama' => 'Kabupaten Halmahera Utara', 'akronim' => 'TOB', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '8204', 'nama' => 'Kabupaten Halmahera Selatan', 'akronim' => 'LBA', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '8205', 'nama' => 'Kabupaten Kepulauan Sula', 'akronim' => 'SNN', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '8206', 'nama' => 'Kabupaten Halmahera Timur', 'akronim' => 'MAB', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '8208', 'nama' => 'Kabupaten Pulau Morotai', 'akronim' => 'MTS', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '8271', 'nama' => 'Kota Ternate', 'akronim' => 'TTE', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '8272', 'nama' => 'Kota Tidore Kepulauan', 'akronim' => 'TDR', 'kode_prov' => '82', 'id_prov' => Provinsi::where('kode', '82')->first()->id],
            ['kode' => '9103', 'nama' => 'Kabupaten Jayapura', 'akronim' => 'JAP', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9105', 'nama' => 'Kabupaten Kepulauan Yapen', 'akronim' => 'SRU', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9106', 'nama' => 'Kabupaten Biak Numfor', 'akronim' => 'BIK', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9110', 'nama' => 'Kabupaten Sarmi', 'akronim' => 'SMI', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9111', 'nama' => 'Kabupaten Keerom', 'akronim' => 'WRS', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9115', 'nama' => 'Kabupaten Waropen', 'akronim' => 'BTW', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9119', 'nama' => 'Kabupaten Supiori', 'akronim' => 'SRW', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9120', 'nama' => 'Kabupaten Mamberamo Raya', 'akronim' => 'BRM', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9171', 'nama' => 'Kota Jayapura', 'akronim' => 'JAP', 'kode_prov' => '91', 'id_prov' => Provinsi::where('kode', '91')->first()->id],
            ['kode' => '9202', 'nama' => 'Kabupaten Manokwari', 'akronim' => 'MNK', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9203', 'nama' => 'Kabupaten Fak Fak', 'akronim' => 'FFK', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9206', 'nama' => 'Kabupaten Teluk Bintuni', 'akronim' => 'BTI', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9207', 'nama' => 'Kabupaten Teluk Wondama', 'akronim' => 'RAS', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9208', 'nama' => 'Kabupaten Kaimana', 'akronim' => 'KMN', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9211', 'nama' => 'Kabupaten Manokwari Selatan', 'akronim' => 'RSK', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9212', 'nama' => 'Kabupaten Pegunungan Arfak', 'akronim' => 'ANG', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
        
        
            ['kode' => '9201', 'nama' => 'Kabupaten Sorong', 'akronim' => 'AMS', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9204', 'nama' => 'Kabupaten Sorong Selatan', 'akronim' => 'TMB', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9205', 'nama' => 'Kabupaten Raja Ampat', 'akronim' => 'WAS', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9209', 'nama' => 'Kabupaten Tambrauw', 'akronim' => 'FEF', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9210', 'nama' => 'Kabupaten Maybrat', 'akronim' => 'AFT', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
            ['kode' => '9271', 'nama' => 'Kota Sorong', 'akronim' => 'SON', 'kode_prov' => '92', 'id_prov' => Provinsi::where('kode', '92')->first()->id],
        
        
            ['kode' => '9301', 'nama' => 'Kabupaten Merauke', 'akronim' => 'MRK', 'kode_prov' => '93', 'id_prov' => Provinsi::where('kode', '93')->first()->id],
            ['kode' => '9302', 'nama' => 'Kabupaten Boven Digoel', 'akronim' => 'TMR', 'kode_prov' => '93', 'id_prov' => Provinsi::where('kode', '93')->first()->id],
            ['kode' => '9303', 'nama' => 'Kabupaten Mappi', 'akronim' => 'KEP', 'kode_prov' => '93', 'id_prov' => Provinsi::where('kode', '93')->first()->id],
            ['kode' => '9304', 'nama' => 'Kabupaten Asmat', 'akronim' => 'AGT', 'kode_prov' => '93', 'id_prov' => Provinsi::where('kode', '93')->first()->id],
        
        
            ['kode' => '9401', 'nama' => 'Kabupaten Nabire', 'akronim' => 'NAB', 'kode_prov' => '94', 'id_prov' => Provinsi::where('kode', '94')->first()->id],
            ['kode' => '9402', 'nama' => 'Kabupaten Puncak Jaya', 'akronim' => 'MUL', 'kode_prov' => '94', 'id_prov' => Provinsi::where('kode', '94')->first()->id],
            ['kode' => '9403', 'nama' => 'Kabupaten Paniai', 'akronim' => 'ERT', 'kode_prov' => '94', 'id_prov' => Provinsi::where('kode', '94')->first()->id],
            ['kode' => '9404', 'nama' => 'Kabupaten Mimika', 'akronim' => 'TIM', 'kode_prov' => '94', 'id_prov' => Provinsi::where('kode', '94')->first()->id],
            ['kode' => '9405', 'nama' => 'Kabupaten Puncak', 'akronim' => 'ILG', 'kode_prov' => '94', 'id_prov' => Provinsi::where('kode', '94')->first()->id],
            ['kode' => '9406', 'nama' => 'Kabupaten Dogiyai', 'akronim' => 'KGM', 'kode_prov' => '94', 'id_prov' => Provinsi::where('kode', '94')->first()->id],
            ['kode' => '9407', 'nama' => 'Kabupaten Intan Jaya', 'akronim' => 'SGP', 'kode_prov' => '94', 'id_prov' => Provinsi::where('kode', '94')->first()->id],
            ['kode' => '9408', 'nama' => 'Kabupaten Deiyai', 'akronim' => 'TIG', 'kode_prov' => '94', 'id_prov' => Provinsi::where('kode', '94')->first()->id],
           
            ['kode' => '9501', 'nama' => 'Kabupaten Jayawijaya', 'akronim' => 'WAM', 'kode_prov' => '95', 'id_prov' => Provinsi::where('kode', '95')->first()->id],
            ['kode' => '9502', 'nama' => 'Kabupaten Pegunungan Bintang', 'akronim' => 'OSB', 'kode_prov' => '95', 'id_prov' => Provinsi::where('kode', '95')->first()->id],
            ['kode' => '9503', 'nama' => 'Kabupaten Yahukimo', 'akronim' => 'SMH', 'kode_prov' => '95', 'id_prov' => Provinsi::where('kode', '95')->first()->id],
            ['kode' => '9504', 'nama' => 'Kabupaten Tolikara', 'akronim' => 'KBG', 'kode_prov' => '95', 'id_prov' => Provinsi::where('kode', '95')->first()->id],
            ['kode' => '9505', 'nama' => 'Kabupaten Mamberamo Tengah', 'akronim' => 'KBK', 'kode_prov' => '95', 'id_prov' => Provinsi::where('kode', '95')->first()->id],
            ['kode' => '9506', 'nama' => 'Kabupaten Yalimo', 'akronim' => 'ELL', 'kode_prov' => '95', 'id_prov' => Provinsi::where('kode', '95')->first()->id],
            ['kode' => '9507', 'nama' => 'Kabupaten Lanny Jaya', 'akronim' => 'TOM', 'kode_prov' => '95', 'id_prov' => Provinsi::where('kode', '95')->first()->id],
            ['kode' => '9508', 'nama' => 'Kabupaten Nduga', 'akronim' => 'KYM', 'kode_prov' => '95', 'id_prov' => Provinsi::where('kode', '95')->first()->id],
            ['kode' => '3572', 'nama' => 'Kota Blitar', 'akronim' => 'BLT', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3573', 'nama' => 'Kota Malang', 'akronim' => 'MLG', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3574', 'nama' => 'Kota Probolinggo', 'akronim' => 'PBL', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3575', 'nama' => 'Kota Pasuruan', 'akronim' => 'PSN', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3576', 'nama' => 'Kota Mojokerto', 'akronim' => 'MJK', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3577', 'nama' => 'Kota Madiun', 'akronim' => 'MAD', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3578', 'nama' => 'Kota Surabaya', 'akronim' => 'SBY', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
            ['kode' => '3579', 'nama' => 'Kota Batu', 'akronim' => 'BTU', 'kode_prov' => '35', 'id_prov' => Provinsi::where('kode', '35')->first()->id],
        
        
            ['kode' => '3601', 'nama' => 'Kabupaten Pandeglang', 'akronim' => 'PDG', 'kode_prov' => '36', 'id_prov' => Provinsi::where('kode', '36')->first()->id],
            ['kode' => '3602', 'nama' => 'Kabupaten Lebak', 'akronim' => 'RKB', 'kode_prov' => '36', 'id_prov' => Provinsi::where('kode', '36')->first()->id],
            ['kode' => '3603', 'nama' => 'Kabupaten Tangerang', 'akronim' => 'TGR', 'kode_prov' => '36', 'id_prov' => Provinsi::where('kode', '36')->first()->id],
            ['kode' => '3604', 'nama' => 'Kabupaten Serang', 'akronim' => 'SRG', 'kode_prov' => '36', 'id_prov' => Provinsi::where('kode', '36')->first()->id],
            ['kode' => '3671', 'nama' => 'Kota Tangerang', 'akronim' => 'TNG', 'kode_prov' => '36', 'id_prov' => Provinsi::where('kode', '36')->first()->id],
            ['kode' => '3672', 'nama' => 'Kota Cilegon', 'akronim' => 'CLG', 'kode_prov' => '36', 'id_prov' => Provinsi::where('kode', '36')->first()->id],
            ['kode' => '3673', 'nama' => 'Kota Serang', 'akronim' => 'SRG', 'kode_prov' => '36', 'id_prov' => Provinsi::where('kode', '36')->first()->id],
            ['kode' => '3674', 'nama' => 'Kota Tangerang Selatan', 'akronim' => 'CPT', 'kode_prov' => '36', 'id_prov' => Provinsi::where('kode', '36')->first()->id],
        
        
            ['kode' => '5101', 'nama' => 'Kabupaten Jembrana', 'akronim' => 'NGA', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
            ['kode' => '5102', 'nama' => 'Kabupaten Tabanan', 'akronim' => 'TAB', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
            ['kode' => '5103', 'nama' => 'Kabupaten Badung', 'akronim' => 'MGW', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
            ['kode' => '5104', 'nama' => 'Kabupaten Gianyar', 'akronim' => 'GIN', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
            ['kode' => '5105', 'nama' => 'Kabupaten Klungkung', 'akronim' => 'SRP', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
            ['kode' => '5106', 'nama' => 'Kabupaten Bangli', 'akronim' => 'BLI', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
            ['kode' => '5107', 'nama' => 'Kabupaten Karangasem', 'akronim' => 'KRA', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
            ['kode' => '5108', 'nama' => 'Kabupaten Buleleng', 'akronim' => 'SGR', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
            ['kode' => '5171', 'nama' => 'Kota Denpasar', 'akronim' => 'DPR', 'kode_prov' => '51', 'id_prov' => Provinsi::where('kode', '51')->first()->id],
        
        
            ['kode' => '5201', 'nama' => 'Kabupaten Lombok Barat', 'akronim' => 'GRG', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5202', 'nama' => 'Kabupaten Lombok Tengah', 'akronim' => 'PYA', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5203', 'nama' => 'Kabupaten Lombok Timur', 'akronim' => 'SEL', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5204', 'nama' => 'Kabupaten Sumbawa', 'akronim' => 'SBW', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5205', 'nama' => 'Kabupaten Dompu', 'akronim' => 'DPU', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5206', 'nama' => 'Kabupaten Bima', 'akronim' => 'WHO', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5207', 'nama' => 'Kabupaten Sumbawa Barat', 'akronim' => 'TLW', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5208', 'nama' => 'Kabupaten Lombok Utara', 'akronim' => 'TJN', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5271', 'nama' => 'Kota Mataram', 'akronim' => 'MTR', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
            ['kode' => '5272', 'nama' => 'Kota Bima', 'akronim' => 'BIM', 'kode_prov' => '52', 'id_prov' => Provinsi::where('kode', '52')->first()->id],
        
        
            ['kode' => '5301', 'nama' => 'Kabupaten Kupang', 'akronim' => 'KPG', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5302', 'nama' => 'Kabupaten Timor Tengah Selatan', 'akronim' => 'SOE', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5303', 'nama' => 'Kabupaten Timor Tengah Utara', 'akronim' => 'KFM', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5304', 'nama' => 'Kabupaten Belu', 'akronim' => 'ATB', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5305', 'nama' => 'Kabupaten Alor', 'akronim' => 'KLB', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5306', 'nama' => 'Kabupaten Flores Timur', 'akronim' => 'LRT', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5307', 'nama' => 'Kabupaten Sikka', 'akronim' => 'MME', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5308', 'nama' => 'Kabupaten Ende', 'akronim' => 'END', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5309', 'nama' => 'Kabupaten Ngada', 'akronim' => 'BJW', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5310', 'nama' => 'Kabupaten Manggarai', 'akronim' => 'RTG', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5311', 'nama' => 'Kabupaten Sumba Timur', 'akronim' => 'WGP', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5312', 'nama' => 'Kabupaten Sumba Barat', 'akronim' => 'WKB', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5313', 'nama' => 'Kabupaten Lembata', 'akronim' => 'LWL', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5314', 'nama' => 'Kabupaten Rote Ndao', 'akronim' => 'BAA', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5315', 'nama' => 'Kabupaten Manggarai Barat', 'akronim' => 'LBJ', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5316', 'nama' => 'Kabupaten Nagekeo', 'akronim' => 'MBY', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5317', 'nama' => 'Kabupaten Sumba Tengah', 'akronim' => 'WBL', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5318', 'nama' => 'Kabupaten Sumba Barat Daya', 'akronim' => 'TAM', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5319', 'nama' => 'Kabupaten Manggarai Timur', 'akronim' => 'BRG', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5320', 'nama' => 'Kabupaten Sabu Raijua', 'akronim' => 'SBB', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5321', 'nama' => 'Kabupaten Malaka', 'akronim' => '', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
            ['kode' => '5371', 'nama' => 'Kota Kupang', 'akronim' => 'KPG', 'kode_prov' => '53', 'id_prov' => Provinsi::where('kode', '53')->first()->id],
        
        
            ['kode' => '6101', 'nama' => 'Kabupaten Sambas', 'akronim' => 'SBS', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6102', 'nama' => 'Kabupaten Mempawah', 'akronim' => 'MPW', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6103', 'nama' => 'Kabupaten Sanggau', 'akronim' => 'SAG', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6104', 'nama' => 'Kabupaten Ketapang', 'akronim' => 'KTP', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6105', 'nama' => 'Kabupaten Sintang', 'akronim' => 'STG', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6106', 'nama' => 'Kabupaten Kapuas Hulu', 'akronim' => 'PTS', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6107', 'nama' => 'Kabupaten Bengkayang', 'akronim' => 'BEK', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6108', 'nama' => 'Kabupaten Landak', 'akronim' => 'NBA', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6109', 'nama' => 'Kabupaten Sekadau', 'akronim' => 'SED', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6110', 'nama' => 'Kabupaten Melawi', 'akronim' => 'NGP', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6111', 'nama' => 'Kabupaten Kayong Utara', 'akronim' => 'SKD', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6112', 'nama' => 'Kabupaten Kubu Raya', 'akronim' => 'SRY', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6171', 'nama' => 'Kota Pontianak', 'akronim' => 'PTK', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
            ['kode' => '6172', 'nama' => 'Kota Singkawang', 'akronim' => 'SKW', 'kode_prov' => '61', 'id_prov' => Provinsi::where('kode', '61')->first()->id],
        
        
            ['kode' => '6201', 'nama' => 'Kabupaten Kotawaringin Barat', 'akronim' => 'PBU', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6202', 'nama' => 'Kabupaten Kotawaringin Timur', 'akronim' => 'SPT', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6203', 'nama' => 'Kabupaten Kapuas', 'akronim' => 'KLK', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6204', 'nama' => 'Kabupaten Barito Selatan', 'akronim' => 'BNT', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6205', 'nama' => 'Kabupaten Barito Utara', 'akronim' => 'MTW', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6206', 'nama' => 'Kabupaten Katingan', 'akronim' => 'KSN', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6207', 'nama' => 'Kabupaten Seruyan', 'akronim' => 'KLP', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6208', 'nama' => 'Kabupaten Sukamara', 'akronim' => 'SKR', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6209', 'nama' => 'Kabupaten Lamandau', 'akronim' => 'NGB', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6210', 'nama' => 'Kabupaten Gunung Mas', 'akronim' => 'KKN', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6211', 'nama' => 'Kabupaten Pulang Pisau', 'akronim' => 'PPS', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6212', 'nama' => 'Kabupaten Murung Raya', 'akronim' => 'PRC', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6213', 'nama' => 'Kabupaten Barito Timur', 'akronim' => 'TML', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6271', 'nama' => 'Kota Palangkaraya', 'akronim' => 'PLK', 'kode_prov' => '62', 'id_prov' => Provinsi::where('kode', '62')->first()->id],
            ['kode' => '6301', 'nama' => 'Kabupaten Tanah Laut', 'akronim' => 'PLI', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6302', 'nama' => 'Kabupaten Kotabaru', 'akronim' => 'KBR', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6303', 'nama' => 'Kabupaten Banjar', 'akronim' => 'MTP', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6304', 'nama' => 'Kabupaten Barito Kuala', 'akronim' => 'MRH', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6305', 'nama' => 'Kabupaten Tapin', 'akronim' => 'RTA', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6306', 'nama' => 'Kabupaten Hulu Sungai Selatan', 'akronim' => 'KGN', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6307', 'nama' => 'Kabupaten Hulu Sungai Tengah', 'akronim' => 'BRB', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6308', 'nama' => 'Kabupaten Hulu Sungai Utara', 'akronim' => 'AMT', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6309', 'nama' => 'Kabupaten Tabalong', 'akronim' => 'TJG', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6310', 'nama' => 'Kabupaten Tanah Bumbu', 'akronim' => 'BLN', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6311', 'nama' => 'Kabupaten Balangan', 'akronim' => 'PRN', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6371', 'nama' => 'Kota Banjarmasin', 'akronim' => 'BJM', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
            ['kode' => '6372', 'nama' => 'Kota Banjarbaru', 'akronim' => 'BJB', 'kode_prov' => '63', 'id_prov' => Provinsi::where('kode', '63')->first()->id],
           
            ['kode' => '6401', 'nama' => 'Kabupaten Paser', 'akronim' => 'TGT', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6402', 'nama' => 'Kabupaten Kutai Kartanegara', 'akronim' => 'TRG', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6403', 'nama' => 'Kabupaten Berau', 'akronim' => 'TNR', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6407', 'nama' => 'Kabupaten Kutai Barat', 'akronim' => 'SDW', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6408', 'nama' => 'Kabupaten Kutai Timur', 'akronim' => 'SGT', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6409', 'nama' => 'Kabupaten Penajam Paser Utara', 'akronim' => 'PNJ', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6411', 'nama' => 'Kabupaten Mahakam Ulu', 'akronim' => '', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6471', 'nama' => 'Kota Balikpapan', 'akronim' => 'BPP', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6472', 'nama' => 'Kota Samarinda', 'akronim' => 'SMR', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
            ['kode' => '6474', 'nama' => 'Kota Bontang', 'akronim' => 'BON', 'kode_prov' => '64', 'id_prov' => Provinsi::where('kode', '64')->first()->id],
        
        
            ['kode' => '6501', 'nama' => 'Kabupaten Bulungan', 'akronim' => 'TJS', 'kode_prov' => '65', 'id_prov' => Provinsi::where('kode', '65')->first()->id],
            ['kode' => '6502', 'nama' => 'Kabupaten Malinau', 'akronim' => 'MLN', 'kode_prov' => '65', 'id_prov' => Provinsi::where('kode', '65')->first()->id],
            ['kode' => '6503', 'nama' => 'Kabupaten Nunukan', 'akronim' => 'NNK', 'kode_prov' => '65', 'id_prov' => Provinsi::where('kode', '65')->first()->id],
            ['kode' => '6504', 'nama' => 'Kabupaten Tana Tidung', 'akronim' => 'TDP', 'kode_prov' => '65', 'id_prov' => Provinsi::where('kode', '65')->first()->id],
            ['kode' => '6571', 'nama' => 'Kota Tarakan', 'akronim' => 'TAR', 'kode_prov' => '65', 'id_prov' => Provinsi::where('kode', '65')->first()->id],
        
        
            ['kode' => '7101', 'nama' => 'Kabupaten Bolaang Mongondow', 'akronim' => 'LLK', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7102', 'nama' => 'Kabupaten Minahasa', 'akronim' => 'TNN', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7103', 'nama' => 'Kabupaten Kepulauan Sangihe', 'akronim' => 'THN', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7104', 'nama' => 'Kabupaten Kepulauan Talaud', 'akronim' => 'MGN', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7105', 'nama' => 'Kabupaten Minahasa Selatan', 'akronim' => 'AMR', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7106', 'nama' => 'Kabupaten Minahasa Utara', 'akronim' => 'ARM', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7107', 'nama' => 'Kabupaten Minahasa Tenggara', 'akronim' => 'RTN', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7108', 'nama' => 'Kabupaten Bolaang Mongondow Utara', 'akronim' => 'BRK', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7109', 'nama' => 'Kabupaten Kepulauan Siau Tagulandang Biaro', 'akronim' => 'ODS', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7110', 'nama' => 'Kabupaten Bolaang Mongondow Timur', 'akronim' => 'TTY', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7111', 'nama' => 'Kabupaten Bolaang Mongondow Selatan', 'akronim' => 'BLU', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7171', 'nama' => 'Kota Manado', 'akronim' => 'MND', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7172', 'nama' => 'Kota Bitung', 'akronim' => 'BIT', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7173', 'nama' => 'Kota Tomohon', 'akronim' => 'TMH', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
            ['kode' => '7174', 'nama' => 'Kota Kotamobagu', 'akronim' => 'KTG', 'kode_prov' => '71', 'id_prov' => Provinsi::where('kode', '71')->first()->id],
        
        
            ['kode' => '7201', 'nama' => 'Kabupaten Banggai', 'akronim' => 'LWK', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7202', 'nama' => 'Kabupaten Poso', 'akronim' => 'PSO', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7203', 'nama' => 'Kabupaten Donggala', 'akronim' => 'DGL', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7204', 'nama' => 'Kabupaten Toli-Toli', 'akronim' => 'TLI', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7205', 'nama' => 'Kabupaten Buol', 'akronim' => 'BUL', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7206', 'nama' => 'Kabupaten Morowali', 'akronim' => 'BGK', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7207', 'nama' => 'Kabupaten Banggai Kepulauan', 'akronim' => 'SKN', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7208', 'nama' => 'Kabupaten Parigi Moutong', 'akronim' => 'PRG', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7209', 'nama' => 'Kabupaten Tojo Una-Una', 'akronim' => 'APN', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7210', 'nama' => 'Kabupaten Sigi', 'akronim' => 'SGB', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7211', 'nama' => 'Kabupaten Banggai Laut', 'akronim' => 'SKN', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7212', 'nama' => 'Kabupaten Morowali Utara', 'akronim' => '', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
            ['kode' => '7271', 'nama' => 'Kota Palu', 'akronim' => 'PAL', 'kode_prov' => '72', 'id_prov' => Provinsi::where('kode', '72')->first()->id],
        
        
            ['kode' => '7301', 'nama' => 'Kabupaten Kepulauan Selayar', 'akronim' => 'BEN', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7302', 'nama' => 'Kabupaten Bulukumba', 'akronim' => 'BLK', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7303', 'nama' => 'Kabupaten Bantaeng', 'akronim' => 'BAN', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7304', 'nama' => 'Kabupaten Jeneponto', 'akronim' => 'JNP', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7305', 'nama' => 'Kabupaten Takalar', 'akronim' => 'TKA', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7306', 'nama' => 'Kabupaten Gowa', 'akronim' => 'SGM', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7307', 'nama' => 'Kabupaten Sinjai', 'akronim' => 'SNJ', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7308', 'nama' => 'Kabupaten Bone', 'akronim' => 'WTP', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7309', 'nama' => 'Kabupaten Maros', 'akronim' => 'MRS', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7310', 'nama' => 'Kabupaten Pangkajene Kepulauan', 'akronim' => 'PKJ', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7311', 'nama' => 'Kabupaten Barru', 'akronim' => 'BAR', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7312', 'nama' => 'Kabupaten Soppeng', 'akronim' => 'WNS', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7313', 'nama' => 'Kabupaten Wajo', 'akronim' => 'SKG', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7314', 'nama' => 'Kabupaten Sidenreng Rappang', 'akronim' => 'SDR', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7315', 'nama' => 'Kabupaten Pinrang', 'akronim' => 'PIN', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7316', 'nama' => 'Kabupaten Enrekang', 'akronim' => 'ENR', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7317', 'nama' => 'Kabupaten Luwu', 'akronim' => 'PLP', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7318', 'nama' => 'Kabupaten Tana Toraja', 'akronim' => 'MAK', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7322', 'nama' => 'Kabupaten Luwu Utara', 'akronim' => 'MSB', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7325', 'nama' => 'Kabupaten Luwu Timur', 'akronim' => 'MLL', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7326', 'nama' => 'Kabupaten Toraja Utara', 'akronim' => 'RTP', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7371', 'nama' => 'Kota Makassar', 'akronim' => 'MKS', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7372', 'nama' => 'Kota Parepare', 'akronim' => 'PRE', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
            ['kode' => '7373', 'nama' => 'Kota Palopo', 'akronim' => 'PLP', 'kode_prov' => '73', 'id_prov' => Provinsi::where('kode', '73')->first()->id],
        
        
            ['kode' => '7401', 'nama' => 'Kabupaten Kolaka', 'akronim' => 'KKA', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7402', 'nama' => 'Kabupaten Konawe', 'akronim' => 'UNH', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7403', 'nama' => 'Kabupaten Muna', 'akronim' => 'RAH', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7404', 'nama' => 'Kabupaten Buton', 'akronim' => 'PSW', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7405', 'nama' => 'Kabupaten Konawe Selatan', 'akronim' => 'ADL', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id],
            ['kode' => '7406', 'nama' => 'Kabupaten Bombana', 'akronim' => 'RMB', 'kode_prov' => '74', 'id_prov' => Provinsi::where('kode', '74')->first()->id]
        ];
        

        foreach ($kabkota as $data) {
            DB::table('kab_kotas')->insert($data);
        }
    }
}
